- name: Vault demo
  hosts: localhost
  connection: local
  tasks:
    - name: Get value from vault
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/demo:ec2-user token={{ token }} url=http://172.31.29.194:8200') }}"