- name: Vault Demo
  hosts: localhost
  connection: local
  tasks:
    - name: Get Values from Vault
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/demo:mypass token={{ token }}   url=http://http://3.236.115.77/:8200') }}"