- name: Frontend
  hosts: all
  become: true

  tasks:
    - name: Disable default nginx module
      ansible.builtin.shell: dnf module disable nginx -y

    - name: Enable nginx 1.24 module
      ansible.builtin.shell: dnf module enable nginx:1.24 -y

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf


