- name: Disable nginx default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx version 1.24
  ansible.builtin.shell: dnf module disable nginx -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed