- name: Frontend
  hosts: all
  become: true

  tasks:
    - name: Disable default nginx module
      ansible.builtin.shell: dnf module disable nginx -y

    - name: Enable nginx 1.24 module
      ansible.builtin.shell: dnf module enable nginx:1.24 -y

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Remove nginx default content
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create nginx http directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Download nginx content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes


